apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers: 
        - name: auth
          image: engrabi/abtech
          ports:
            - containerPort: 5000 
          envFrom:
            - configMapRef:
                name: auth-config-map
            - secretRef:
                name: auth-secrets
