name: bookbeacon
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  get: ^4.6.5
  fast_cached_network_image: ^1.2.0
  path_provider: ^2.1.1
  cloud_firestore: ^4.13.1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  animated_notch_bottom_bar: ^1.0.0
  url_launcher: ^6.1.14
  popover_gtk: ^0.2.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
